#!/usr/bin/env python
from __future__ import with_statement, print_function
import os
from os.path import join, dirname, realpath
import re
import shutil
import subprocess
import sys
import tempfile
from distutils.spawn import find_executable

OTHER_SCRIPTS = ['remove-trailing-whitepace-hook.sh']

def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    if out is not None:
        out = out.decode('ascii')
    code = proc.wait()
    return out, code


def main():
    for o in OTHER_SCRIPTS:
        out = system(join(dirname(realpath(__file__)), o))
        print(out)

    sys.exit(1)

    flake8_bin = find_executable('flake8')
    if flake8_bin is None:
        print('flake8 command not found! (pip install flake8)', file=sys.stderr)
        sys.exit(1)

    modified = re.compile('^[AM]+\s+(?P<name>.*\.py)', re.MULTILINE)
    files = system('git', 'status', '--porcelain')
    files = modified.findall(files)

    tempdir = tempfile.mkdtemp()
    try:
        for name in files:
            filename = os.path.join(tempdir, name)
            filepath = os.path.dirname(filename)
            if not os.path.exists(filepath):
                os.makedirs(filepath)
            with open(filename, 'wb') as f:
                system('git', 'show', ':' + name, stdout=f)
        output = system(flake8_bin, '.', cwd=tempdir)
    finally:
        shutil.rmtree(tempdir)
    if output:
        print(output, end='')
        sys.exit(1)


if __name__ == '__main__':
    main()
